# Generated by Django 4.0.4 on 2022-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, upload_to='AuthorsImg/media/%Y/%m/%d', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='CategoryImg/media/%Y/%m/%d', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='newsImg/media/%Y/%m/%d', verbose_name='Загрузить фото'),
        ),
    ]
