# Generated by Django 4.0.4 on 2022-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_author_photo_alter_category_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='url'),
        ),
    ]
