# Generated by Django 4.0.4 on 2022-05-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='mail',
            field=models.EmailField(default='test@gmail.com', max_length=254, verbose_name='Адрес электронной почты'),
        ),
    ]
