# Generated by Django 4.0.4 on 2022-05-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_author_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Адрес электронной почты'),
        ),
    ]
